dist: trusty
sudo: required
language: generic

services:
    - docker

install:
    docker pull debian:stretch

script:
    docker run -v "$PWD:/workspace/temper-exporter" -w /workspace/temper-exporter debian:stretch './.travis-build.sh'
